services:
    db:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dvops-fweb-wsc-web-tech-portal
            MYSQL_ROOT_PASSWORD: adev
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3307:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10

    app:
        build: .
        container_name: dvops-fweb-wsc-web-tech-portal
        image: ${DOCKER_USERNAME}/dvops-fweb-wsc-web-tech-portal:latest
        restart: unless-stopped
        environment:
            DB_HOST: mysql
            DB_DATABASE: dvops_fweb_wsc_web_tech_portal
        command: [ "migrate" ]
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8000:80
        volumes:
            - .env:/var/www/html/.env
            - app_storage:/var/www/html/storage

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        container_name: phpmyadmin
        ports:
            - 8001:80
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: adev

volumes:
    mysql_data:
    app_storage:
